#FROM alpine

# STEP4-4では以下は変更しない
#CMD ["python", "-V"]


FROM python:3.9.6-slim-buster

COPY db/items.db db/

WORKDIR /python

COPY python/requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY python/ .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9000"]
